# Generated by Django 5.0.6 on 2024-06-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=50, unique='true')),
                ('Details', models.CharField(max_length=100)),
                ('Fees', models.IntegerField(max_length=10)),
                ('Duration', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=50)),
                ('Mode', models.CharField(max_length=10)),
            ],
        ),
    ]
